export const weatherImages: { [key: string]: any } = {
  1003: require("../assets/images/partiallycloudy.png"),
  1063: require("../assets/images/rain.png"),
  // 1030: require("../assets/images/moderaterain.png"),
  1189: require("../assets/images/moderaterain.png"),
  "Patchy rain possible": require("../assets/images/patcyrainpossible.png"),
  1000: require("../assets/images/sunny.png"),
  Clear: require("../assets/images/sun.png"),
  1009: require("../assets/images/overcast.png"),
  1006: require("../assets/images/cloudy.png"),
  1180: require("../assets/images/rain.png"),
  1183: require("../assets/images/rain.png"),
  1186: require("../assets/images/moderateraintimes.png"),
  1195: require("../assets/images/heavyrain.png"),
  1192: require("../assets/images/heavyraintimes.png"),
  1201: require("../assets/images/moderateheavyfreezingrain.png"),
  1243: require("../assets/images/moderateheavyrainshower.png"),
  1276: require("../assets/images/moderateheavyrainthunder.png"),
  3742: require("../assets/images/other.png"),
};

// {
//   "Partly cloudy": require("../assets/images/partiallycloudy.png"),
//   "Patchy rain nearby": require("../assets/images/rain.png"),
//   "Moderate rain": require("../assets/images/moderaterain.png"),
//   "Patchy rain possible": require("../assets/images/patcyrainpossible.png"),
//   Sunny: require("../assets/images/sunny.png"),
//   Clear: require("../assets/images/sun.png"),
//   Overcast: require("../assets/images/overcast.png"),
//   Cloudy: require("../assets/images/cloudy.png"),
//   "Light rain": require("../assets/images/rain.png"),
//   "Moderate rain at times": require("../assets/images/moderateraintimes.png"),
//   "Heavy rain": require("../assets/images/heavyrain.png"),
//   "Heavy rain at times": require("../assets/images/heavyraintimes.png"),
//   "Moderate or heavy freezing rain": require("../assets/images/moderateheavyfreezingrain.png"),
//   "Moderate or heavy rain shower": require("../assets/images/moderateheavyrainshower.png"),
//   "Moderate or heavy rain with thunder": require("../assets/images/moderateheavyrainthunder.png"),
//   other: require("../assets/images/other.png"),
// };
